<?php echo $this->doctype('HTML5');?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php echo $this->headTitle("AppStart");?>
<?php echo $this->headStyle()
					->appendStyle($this->baseUrl('css/style.css'))
					->appendStyle($this->baseUrl('css/reset.css'))
					->appendStyle($this->baseUrl('css/structure.css'));
?>
<?php echo $this->headScript();?>
</head>
<body>
<?php 
	$zenAuth = Zend_Auth::getInstance();
  	$zendRead = $zenAuth->getStorage()->read();
?>
<div id="wrapper">
  <header id="header">
    <h1></h1>
    <nav id="top-nav" >
      <ul>
        <li class="current"><a href="#">Welcome <span><?php echo $zendRead->first_name." ".$zendRead->last_name ?></span> </a></li>
        <li class="logout"><a href="#"  >Logout</a></li>
      </ul>
    </nav>
    <div style="clear:both;"></div>
    <nav id="main-nav">
      <?php echo $this->navigation()->menu() ?> 
    </nav>
    
    <!-- with images -->
    <div id="breadcrumb">
      <?php echo $this->navigation()
  				  ->breadcrumbs()
  				  ->setMinDepth(0)
  				  ->setLinkLast(false)
  				  ->setRenderInvisible(true)
  				  ->setSeparator(""); ?>
    </div>
  </header>
  <!-- #header-->
  <div style="clear:both;"></div>
  <div id="content">
    <?php echo $this->layout ()->content; ?>
    <br style="clear:both" />
  </div>
  <!-- #content-->
  
  <footer id="footer"> Copyright by AK Systems Inc 2012</footer>
  <!-- #footer --> 
  
</div>
<!-- #wrapper -->
</body>
</html>